import type { Metadata } from "next";
import './globals.css'
import HeaderOrSidebar from "./components/HeaderOrSidebar";

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <HeaderOrSidebar />
        {children}
      </body>
    </html>
  );
}
